### ISSUE TITLE
The app disappears completely when you want to hide the icon.

### ISSUE THREAD

**Issue by shirou-jeff** [jruesga/PhotoPhase#36]
#### Expected behavior
The icon is expected to be hidden from the device, but the application can still be used.

#### Actual behavior
The application disappears completely from the device when you want to hide it from the launcher.

#### How to reproduce
1. Download the application. 
2. Install. 
3. Try to hide the launcher icon. 
4. Try to find the application move mind on the device. 
5. The application has completely disappeared and needs to be reinstalled to reuse.

* Browser: photophase V 2.7.0
* Operating system: Android 5.1.1

#### Recording Of The Bug
https://youtu.be/DrFsaHSleEo
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/the-app-disappears-completely-when-you-want-to-hide-the-icon">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jruesga** [comment]
@shirou-jeff that's the expected behaviour. The app can still being accessed through the launcher live wallperper chooser activity, normally by long tapping on an empty launcher area, wallpapers and photophase. You got a preview of the lwp and a button to the settings activity. Removing the icon is an option for users than do not need to fullfill the launcher drawer with an icon that they not going to use frequently.
